# This is a basic workflow to help you get started with Actions

name: 'CI-build'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - 'main'
      - 'master'
      - 'v-*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'
      - 'master'
      - 'v-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build", but i testing and add job from documentation :)
  build:
    runs-on: ubuntu-22.04
    #    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Install curl-dev
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check

      #      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      #      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      #      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      #      - name: Check out repository code
      #        uses: actions/checkout@v3
      #      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      #      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      #      - name: List files in the repository
      #        run: |
      #          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

#      - name: GitHub Actions Demo
#                - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#                - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#                - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#                - name: Check out repository code
#                  uses: actions/checkout@v3
#                - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#                - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#                - name: List files in the repository
#                  run: |
#                    ls ${{ github.workspace }}
#                - run: echo "ğŸ This job's status is ${{ job.status }}."
#      - name: List Tests
#        run: ls .;echo "---build";ls build/;echo "---test-results"; ls build/test-results/;echo "---jvmTest"; ls build/test-results/jvmTest/
#
#      - name: Test Report
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: Unit Test Results
#          path: build/test-results/**/*.xml
#          reporter: java-junit
